# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-25 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20170213_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=90, unique=True, verbose_name='Slug'),
        ),
    ]
