# Generated by Django 2.2 on 2020-12-23 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200624_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=None, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(on_delete=None, to='blog.Blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_set',
            field=models.ForeignKey(on_delete=None, related_name='blog_posts', to='pinax_images.ImageSet'),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='post',
            field=models.ForeignKey(on_delete=None, related_name='review_comments', to='blog.Post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='author',
            field=models.ForeignKey(on_delete=None, related_name='revisions', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='post',
            field=models.ForeignKey(on_delete=None, related_name='revisions', to='blog.Post', verbose_name='Post'),
        ),
    ]
